//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  siteSettings: SiteSettings;
  siteSettingsConnection: SiteSettingsConnection;
  course: Course;
  courseConnection: CourseConnection;
  blogPost: BlogPost;
  blogPostConnection: BlogPostConnection;
  legalPage: LegalPage;
  legalPageConnection: LegalPageConnection;
  faqGroup: FaqGroup;
  faqGroupConnection: FaqGroupConnection;
  testimonial: Testimonial;
  testimonialConnection: TestimonialConnection;
  teamMember: TeamMember;
  teamMemberConnection: TeamMemberConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteSettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteSettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteSettingsFilter>;
};


export type QueryCourseArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCourseConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CourseFilter>;
};


export type QueryBlogPostArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlogPostConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogPostFilter>;
};


export type QueryLegalPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryLegalPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LegalPageFilter>;
};


export type QueryFaqGroupArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFaqGroupConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FaqGroupFilter>;
};


export type QueryTestimonialArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTestimonialConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimonialFilter>;
};


export type QueryTeamMemberArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTeamMemberConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamMemberFilter>;
};

export type DocumentFilter = {
  siteSettings?: InputMaybe<SiteSettingsFilter>;
  course?: InputMaybe<CourseFilter>;
  blogPost?: InputMaybe<BlogPostFilter>;
  legalPage?: InputMaybe<LegalPageFilter>;
  faqGroup?: InputMaybe<FaqGroupFilter>;
  testimonial?: InputMaybe<TestimonialFilter>;
  teamMember?: InputMaybe<TeamMemberFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = SiteSettings | Course | BlogPost | LegalPage | FaqGroup | Testimonial | TeamMember | Folder;

export type SiteSettingsSocial = {
  __typename?: 'SiteSettingsSocial';
  facebook?: Maybe<Scalars['String']['output']>;
  twitter?: Maybe<Scalars['String']['output']>;
  linkedin?: Maybe<Scalars['String']['output']>;
  instagram?: Maybe<Scalars['String']['output']>;
  youtube?: Maybe<Scalars['String']['output']>;
};

export type SiteSettingsCompanyStats = {
  __typename?: 'SiteSettingsCompanyStats';
  value: Scalars['String']['output'];
  label: Scalars['String']['output'];
};

export type SiteSettingsTrustLogos = {
  __typename?: 'SiteSettingsTrustLogos';
  name: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
};

export type SiteSettings = Node & Document & {
  __typename?: 'SiteSettings';
  siteName?: Maybe<Scalars['String']['output']>;
  tagline?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  social?: Maybe<SiteSettingsSocial>;
  companyStats?: Maybe<Array<Maybe<SiteSettingsCompanyStats>>>;
  trustLogos?: Maybe<Array<Maybe<SiteSettingsTrustLogos>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SiteSettingsSocialFilter = {
  facebook?: InputMaybe<StringFilter>;
  twitter?: InputMaybe<StringFilter>;
  linkedin?: InputMaybe<StringFilter>;
  instagram?: InputMaybe<StringFilter>;
  youtube?: InputMaybe<StringFilter>;
};

export type SiteSettingsCompanyStatsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type SiteSettingsTrustLogosFilter = {
  name?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type SiteSettingsFilter = {
  siteName?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  social?: InputMaybe<SiteSettingsSocialFilter>;
  companyStats?: InputMaybe<SiteSettingsCompanyStatsFilter>;
  trustLogos?: InputMaybe<SiteSettingsTrustLogosFilter>;
};

export type SiteSettingsConnectionEdges = {
  __typename?: 'SiteSettingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<SiteSettings>;
};

export type SiteSettingsConnection = Connection & {
  __typename?: 'SiteSettingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteSettingsConnectionEdges>>>;
};

export type CourseHeroStats = {
  __typename?: 'CourseHeroStats';
  value: Scalars['String']['output'];
  label: Scalars['String']['output'];
};

export type CourseHero = {
  __typename?: 'CourseHero';
  stats?: Maybe<Array<Maybe<CourseHeroStats>>>;
};

export type CourseModules = {
  __typename?: 'CourseModules';
  title: Scalars['String']['output'];
  duration?: Maybe<Scalars['String']['output']>;
};

export type CourseCertificate = {
  __typename?: 'CourseCertificate';
  delivery?: Maybe<Scalars['String']['output']>;
  validity?: Maybe<Scalars['String']['output']>;
  accepted?: Maybe<Scalars['String']['output']>;
};

export type CourseFaqs = {
  __typename?: 'CourseFaqs';
  q: Scalars['String']['output'];
  a: Scalars['String']['output'];
};

export type Course = Node & Document & {
  __typename?: 'Course';
  slug: Scalars['String']['output'];
  title: Scalars['String']['output'];
  eyebrow?: Maybe<Scalars['String']['output']>;
  tagline?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  color?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  summary?: Maybe<Scalars['String']['output']>;
  hero?: Maybe<CourseHero>;
  outcomes?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  modules?: Maybe<Array<Maybe<CourseModules>>>;
  accreditations?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  certificate?: Maybe<CourseCertificate>;
  priceFrom?: Maybe<Scalars['Float']['output']>;
  priceNote?: Maybe<Scalars['String']['output']>;
  faqs?: Maybe<Array<Maybe<CourseFaqs>>>;
  enrollId?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type CourseHeroStatsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type CourseHeroFilter = {
  stats?: InputMaybe<CourseHeroStatsFilter>;
};

export type CourseModulesFilter = {
  title?: InputMaybe<StringFilter>;
  duration?: InputMaybe<StringFilter>;
};

export type CourseCertificateFilter = {
  delivery?: InputMaybe<StringFilter>;
  validity?: InputMaybe<StringFilter>;
  accepted?: InputMaybe<StringFilter>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type CourseFaqsFilter = {
  q?: InputMaybe<StringFilter>;
  a?: InputMaybe<StringFilter>;
};

export type CourseFilter = {
  slug?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  eyebrow?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  color?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  image?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  hero?: InputMaybe<CourseHeroFilter>;
  outcomes?: InputMaybe<StringFilter>;
  modules?: InputMaybe<CourseModulesFilter>;
  accreditations?: InputMaybe<StringFilter>;
  certificate?: InputMaybe<CourseCertificateFilter>;
  priceFrom?: InputMaybe<NumberFilter>;
  priceNote?: InputMaybe<StringFilter>;
  faqs?: InputMaybe<CourseFaqsFilter>;
  enrollId?: InputMaybe<StringFilter>;
};

export type CourseConnectionEdges = {
  __typename?: 'CourseConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Course>;
};

export type CourseConnection = Connection & {
  __typename?: 'CourseConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CourseConnectionEdges>>>;
};

export type BlogPostAuthor = {
  __typename?: 'BlogPostAuthor';
  name: Scalars['String']['output'];
  role?: Maybe<Scalars['String']['output']>;
};

export type BlogPost = Node & Document & {
  __typename?: 'BlogPost';
  title: Scalars['String']['output'];
  excerpt?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  author?: Maybe<BlogPostAuthor>;
  publishedAt: Scalars['String']['output'];
  readMinutes?: Maybe<Scalars['Float']['output']>;
  heroTone?: Maybe<Scalars['String']['output']>;
  heroIcon?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BlogPostAuthorFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type BlogPostFilter = {
  title?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  author?: InputMaybe<BlogPostAuthorFilter>;
  publishedAt?: InputMaybe<DatetimeFilter>;
  readMinutes?: InputMaybe<NumberFilter>;
  heroTone?: InputMaybe<StringFilter>;
  heroIcon?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type BlogPostConnectionEdges = {
  __typename?: 'BlogPostConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<BlogPost>;
};

export type BlogPostConnection = Connection & {
  __typename?: 'BlogPostConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BlogPostConnectionEdges>>>;
};

export type LegalPage = Node & Document & {
  __typename?: 'LegalPage';
  title: Scalars['String']['output'];
  effectiveDate?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type LegalPageFilter = {
  title?: InputMaybe<StringFilter>;
  effectiveDate?: InputMaybe<DatetimeFilter>;
  intro?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type LegalPageConnectionEdges = {
  __typename?: 'LegalPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<LegalPage>;
};

export type LegalPageConnection = Connection & {
  __typename?: 'LegalPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<LegalPageConnectionEdges>>>;
};

export type FaqGroupItems = {
  __typename?: 'FaqGroupItems';
  q: Scalars['String']['output'];
  a: Scalars['String']['output'];
};

export type FaqGroup = Node & Document & {
  __typename?: 'FaqGroup';
  category: Scalars['String']['output'];
  order?: Maybe<Scalars['Float']['output']>;
  items?: Maybe<Array<Maybe<FaqGroupItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FaqGroupItemsFilter = {
  q?: InputMaybe<StringFilter>;
  a?: InputMaybe<StringFilter>;
};

export type FaqGroupFilter = {
  category?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  items?: InputMaybe<FaqGroupItemsFilter>;
};

export type FaqGroupConnectionEdges = {
  __typename?: 'FaqGroupConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<FaqGroup>;
};

export type FaqGroupConnection = Connection & {
  __typename?: 'FaqGroupConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FaqGroupConnectionEdges>>>;
};

export type TestimonialStat = {
  __typename?: 'TestimonialStat';
  value?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type Testimonial = Node & Document & {
  __typename?: 'Testimonial';
  quote: Scalars['String']['output'];
  name: Scalars['String']['output'];
  role?: Maybe<Scalars['String']['output']>;
  company?: Maybe<Scalars['String']['output']>;
  stat?: Maybe<TestimonialStat>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TestimonialStatFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type TestimonialFilter = {
  quote?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  company?: InputMaybe<StringFilter>;
  stat?: InputMaybe<TestimonialStatFilter>;
  featured?: InputMaybe<BooleanFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type TestimonialConnectionEdges = {
  __typename?: 'TestimonialConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Testimonial>;
};

export type TestimonialConnection = Connection & {
  __typename?: 'TestimonialConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TestimonialConnectionEdges>>>;
};

export type TeamMember = Node & Document & {
  __typename?: 'TeamMember';
  name: Scalars['String']['output'];
  role?: Maybe<Scalars['String']['output']>;
  bio?: Maybe<Scalars['String']['output']>;
  linkedin?: Maybe<Scalars['String']['output']>;
  twitter?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TeamMemberFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  bio?: InputMaybe<StringFilter>;
  linkedin?: InputMaybe<StringFilter>;
  twitter?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type TeamMemberConnectionEdges = {
  __typename?: 'TeamMemberConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<TeamMember>;
};

export type TeamMemberConnection = Connection & {
  __typename?: 'TeamMemberConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TeamMemberConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSiteSettings: SiteSettings;
  createSiteSettings: SiteSettings;
  updateCourse: Course;
  createCourse: Course;
  updateBlogPost: BlogPost;
  createBlogPost: BlogPost;
  updateLegalPage: LegalPage;
  createLegalPage: LegalPage;
  updateFaqGroup: FaqGroup;
  createFaqGroup: FaqGroup;
  updateTestimonial: Testimonial;
  createTestimonial: Testimonial;
  updateTeamMember: TeamMember;
  createTeamMember: TeamMember;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSiteSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteSettingsMutation;
};


export type MutationCreateSiteSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteSettingsMutation;
};


export type MutationUpdateCourseArgs = {
  relativePath: Scalars['String']['input'];
  params: CourseMutation;
};


export type MutationCreateCourseArgs = {
  relativePath: Scalars['String']['input'];
  params: CourseMutation;
};


export type MutationUpdateBlogPostArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogPostMutation;
};


export type MutationCreateBlogPostArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogPostMutation;
};


export type MutationUpdateLegalPageArgs = {
  relativePath: Scalars['String']['input'];
  params: LegalPageMutation;
};


export type MutationCreateLegalPageArgs = {
  relativePath: Scalars['String']['input'];
  params: LegalPageMutation;
};


export type MutationUpdateFaqGroupArgs = {
  relativePath: Scalars['String']['input'];
  params: FaqGroupMutation;
};


export type MutationCreateFaqGroupArgs = {
  relativePath: Scalars['String']['input'];
  params: FaqGroupMutation;
};


export type MutationUpdateTestimonialArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialMutation;
};


export type MutationCreateTestimonialArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialMutation;
};


export type MutationUpdateTeamMemberArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMemberMutation;
};


export type MutationCreateTeamMemberArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMemberMutation;
};

export type DocumentUpdateMutation = {
  siteSettings?: InputMaybe<SiteSettingsMutation>;
  course?: InputMaybe<CourseMutation>;
  blogPost?: InputMaybe<BlogPostMutation>;
  legalPage?: InputMaybe<LegalPageMutation>;
  faqGroup?: InputMaybe<FaqGroupMutation>;
  testimonial?: InputMaybe<TestimonialMutation>;
  teamMember?: InputMaybe<TeamMemberMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  siteSettings?: InputMaybe<SiteSettingsMutation>;
  course?: InputMaybe<CourseMutation>;
  blogPost?: InputMaybe<BlogPostMutation>;
  legalPage?: InputMaybe<LegalPageMutation>;
  faqGroup?: InputMaybe<FaqGroupMutation>;
  testimonial?: InputMaybe<TestimonialMutation>;
  teamMember?: InputMaybe<TeamMemberMutation>;
};

export type SiteSettingsSocialMutation = {
  facebook?: InputMaybe<Scalars['String']['input']>;
  twitter?: InputMaybe<Scalars['String']['input']>;
  linkedin?: InputMaybe<Scalars['String']['input']>;
  instagram?: InputMaybe<Scalars['String']['input']>;
  youtube?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSettingsCompanyStatsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSettingsTrustLogosMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSettingsMutation = {
  siteName?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  social?: InputMaybe<SiteSettingsSocialMutation>;
  companyStats?: InputMaybe<Array<InputMaybe<SiteSettingsCompanyStatsMutation>>>;
  trustLogos?: InputMaybe<Array<InputMaybe<SiteSettingsTrustLogosMutation>>>;
};

export type CourseHeroStatsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type CourseHeroMutation = {
  stats?: InputMaybe<Array<InputMaybe<CourseHeroStatsMutation>>>;
};

export type CourseModulesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  duration?: InputMaybe<Scalars['String']['input']>;
};

export type CourseCertificateMutation = {
  delivery?: InputMaybe<Scalars['String']['input']>;
  validity?: InputMaybe<Scalars['String']['input']>;
  accepted?: InputMaybe<Scalars['String']['input']>;
};

export type CourseFaqsMutation = {
  q?: InputMaybe<Scalars['String']['input']>;
  a?: InputMaybe<Scalars['String']['input']>;
};

export type CourseMutation = {
  slug?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  color?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  hero?: InputMaybe<CourseHeroMutation>;
  outcomes?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  modules?: InputMaybe<Array<InputMaybe<CourseModulesMutation>>>;
  accreditations?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  certificate?: InputMaybe<CourseCertificateMutation>;
  priceFrom?: InputMaybe<Scalars['Float']['input']>;
  priceNote?: InputMaybe<Scalars['String']['input']>;
  faqs?: InputMaybe<Array<InputMaybe<CourseFaqsMutation>>>;
  enrollId?: InputMaybe<Scalars['String']['input']>;
};

export type BlogPostAuthorMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
};

export type BlogPostMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<BlogPostAuthorMutation>;
  publishedAt?: InputMaybe<Scalars['String']['input']>;
  readMinutes?: InputMaybe<Scalars['Float']['input']>;
  heroTone?: InputMaybe<Scalars['String']['input']>;
  heroIcon?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type LegalPageMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  effectiveDate?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type FaqGroupItemsMutation = {
  q?: InputMaybe<Scalars['String']['input']>;
  a?: InputMaybe<Scalars['String']['input']>;
};

export type FaqGroupMutation = {
  category?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  items?: InputMaybe<Array<InputMaybe<FaqGroupItemsMutation>>>;
};

export type TestimonialStatMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type TestimonialMutation = {
  quote?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  company?: InputMaybe<Scalars['String']['input']>;
  stat?: InputMaybe<TestimonialStatMutation>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type TeamMemberMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['String']['input']>;
  linkedin?: InputMaybe<Scalars['String']['input']>;
  twitter?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type SiteSettingsPartsFragment = { __typename: 'SiteSettings', siteName?: string | null, tagline?: string | null, phone?: string | null, email?: string | null, social?: { __typename: 'SiteSettingsSocial', facebook?: string | null, twitter?: string | null, linkedin?: string | null, instagram?: string | null, youtube?: string | null } | null, companyStats?: Array<{ __typename: 'SiteSettingsCompanyStats', value: string, label: string } | null> | null, trustLogos?: Array<{ __typename: 'SiteSettingsTrustLogos', name: string, label?: string | null } | null> | null };

export type CoursePartsFragment = { __typename: 'Course', slug: string, title: string, eyebrow?: string | null, tagline?: string | null, category?: string | null, color?: string | null, icon?: string | null, image?: string | null, summary?: string | null, outcomes?: Array<string | null> | null, accreditations?: Array<string | null> | null, priceFrom?: number | null, priceNote?: string | null, enrollId?: string | null, hero?: { __typename: 'CourseHero', stats?: Array<{ __typename: 'CourseHeroStats', value: string, label: string } | null> | null } | null, modules?: Array<{ __typename: 'CourseModules', title: string, duration?: string | null } | null> | null, certificate?: { __typename: 'CourseCertificate', delivery?: string | null, validity?: string | null, accepted?: string | null } | null, faqs?: Array<{ __typename: 'CourseFaqs', q: string, a: string } | null> | null };

export type BlogPostPartsFragment = { __typename: 'BlogPost', title: string, excerpt?: string | null, category?: string | null, publishedAt: string, readMinutes?: number | null, heroTone?: string | null, heroIcon?: string | null, body?: any | null, author?: { __typename: 'BlogPostAuthor', name: string, role?: string | null } | null };

export type LegalPagePartsFragment = { __typename: 'LegalPage', title: string, effectiveDate?: string | null, intro?: string | null, body?: any | null };

export type FaqGroupPartsFragment = { __typename: 'FaqGroup', category: string, order?: number | null, items?: Array<{ __typename: 'FaqGroupItems', q: string, a: string } | null> | null };

export type TestimonialPartsFragment = { __typename: 'Testimonial', quote: string, name: string, role?: string | null, company?: string | null, featured?: boolean | null, order?: number | null, stat?: { __typename: 'TestimonialStat', value?: string | null, label?: string | null } | null };

export type TeamMemberPartsFragment = { __typename: 'TeamMember', name: string, role?: string | null, bio?: string | null, linkedin?: string | null, twitter?: string | null, order?: number | null };

export type SiteSettingsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteSettingsQuery = { __typename?: 'Query', siteSettings: { __typename: 'SiteSettings', id: string, siteName?: string | null, tagline?: string | null, phone?: string | null, email?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, social?: { __typename: 'SiteSettingsSocial', facebook?: string | null, twitter?: string | null, linkedin?: string | null, instagram?: string | null, youtube?: string | null } | null, companyStats?: Array<{ __typename: 'SiteSettingsCompanyStats', value: string, label: string } | null> | null, trustLogos?: Array<{ __typename: 'SiteSettingsTrustLogos', name: string, label?: string | null } | null> | null } };

export type SiteSettingsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteSettingsFilter>;
}>;


export type SiteSettingsConnectionQuery = { __typename?: 'Query', siteSettingsConnection: { __typename?: 'SiteSettingsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteSettingsConnectionEdges', cursor: string, node?: { __typename: 'SiteSettings', id: string, siteName?: string | null, tagline?: string | null, phone?: string | null, email?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, social?: { __typename: 'SiteSettingsSocial', facebook?: string | null, twitter?: string | null, linkedin?: string | null, instagram?: string | null, youtube?: string | null } | null, companyStats?: Array<{ __typename: 'SiteSettingsCompanyStats', value: string, label: string } | null> | null, trustLogos?: Array<{ __typename: 'SiteSettingsTrustLogos', name: string, label?: string | null } | null> | null } | null } | null> | null } };

export type CourseQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CourseQuery = { __typename?: 'Query', course: { __typename: 'Course', id: string, slug: string, title: string, eyebrow?: string | null, tagline?: string | null, category?: string | null, color?: string | null, icon?: string | null, image?: string | null, summary?: string | null, outcomes?: Array<string | null> | null, accreditations?: Array<string | null> | null, priceFrom?: number | null, priceNote?: string | null, enrollId?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'CourseHero', stats?: Array<{ __typename: 'CourseHeroStats', value: string, label: string } | null> | null } | null, modules?: Array<{ __typename: 'CourseModules', title: string, duration?: string | null } | null> | null, certificate?: { __typename: 'CourseCertificate', delivery?: string | null, validity?: string | null, accepted?: string | null } | null, faqs?: Array<{ __typename: 'CourseFaqs', q: string, a: string } | null> | null } };

export type CourseConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CourseFilter>;
}>;


export type CourseConnectionQuery = { __typename?: 'Query', courseConnection: { __typename?: 'CourseConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CourseConnectionEdges', cursor: string, node?: { __typename: 'Course', id: string, slug: string, title: string, eyebrow?: string | null, tagline?: string | null, category?: string | null, color?: string | null, icon?: string | null, image?: string | null, summary?: string | null, outcomes?: Array<string | null> | null, accreditations?: Array<string | null> | null, priceFrom?: number | null, priceNote?: string | null, enrollId?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'CourseHero', stats?: Array<{ __typename: 'CourseHeroStats', value: string, label: string } | null> | null } | null, modules?: Array<{ __typename: 'CourseModules', title: string, duration?: string | null } | null> | null, certificate?: { __typename: 'CourseCertificate', delivery?: string | null, validity?: string | null, accepted?: string | null } | null, faqs?: Array<{ __typename: 'CourseFaqs', q: string, a: string } | null> | null } | null } | null> | null } };

export type BlogPostQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BlogPostQuery = { __typename?: 'Query', blogPost: { __typename: 'BlogPost', id: string, title: string, excerpt?: string | null, category?: string | null, publishedAt: string, readMinutes?: number | null, heroTone?: string | null, heroIcon?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, author?: { __typename: 'BlogPostAuthor', name: string, role?: string | null } | null } };

export type BlogPostConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogPostFilter>;
}>;


export type BlogPostConnectionQuery = { __typename?: 'Query', blogPostConnection: { __typename?: 'BlogPostConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BlogPostConnectionEdges', cursor: string, node?: { __typename: 'BlogPost', id: string, title: string, excerpt?: string | null, category?: string | null, publishedAt: string, readMinutes?: number | null, heroTone?: string | null, heroIcon?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, author?: { __typename: 'BlogPostAuthor', name: string, role?: string | null } | null } | null } | null> | null } };

export type LegalPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type LegalPageQuery = { __typename?: 'Query', legalPage: { __typename: 'LegalPage', id: string, title: string, effectiveDate?: string | null, intro?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type LegalPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LegalPageFilter>;
}>;


export type LegalPageConnectionQuery = { __typename?: 'Query', legalPageConnection: { __typename?: 'LegalPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'LegalPageConnectionEdges', cursor: string, node?: { __typename: 'LegalPage', id: string, title: string, effectiveDate?: string | null, intro?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type FaqGroupQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FaqGroupQuery = { __typename?: 'Query', faqGroup: { __typename: 'FaqGroup', id: string, category: string, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'FaqGroupItems', q: string, a: string } | null> | null } };

export type FaqGroupConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FaqGroupFilter>;
}>;


export type FaqGroupConnectionQuery = { __typename?: 'Query', faqGroupConnection: { __typename?: 'FaqGroupConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FaqGroupConnectionEdges', cursor: string, node?: { __typename: 'FaqGroup', id: string, category: string, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'FaqGroupItems', q: string, a: string } | null> | null } | null } | null> | null } };

export type TestimonialQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TestimonialQuery = { __typename?: 'Query', testimonial: { __typename: 'Testimonial', id: string, quote: string, name: string, role?: string | null, company?: string | null, featured?: boolean | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, stat?: { __typename: 'TestimonialStat', value?: string | null, label?: string | null } | null } };

export type TestimonialConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimonialFilter>;
}>;


export type TestimonialConnectionQuery = { __typename?: 'Query', testimonialConnection: { __typename?: 'TestimonialConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TestimonialConnectionEdges', cursor: string, node?: { __typename: 'Testimonial', id: string, quote: string, name: string, role?: string | null, company?: string | null, featured?: boolean | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, stat?: { __typename: 'TestimonialStat', value?: string | null, label?: string | null } | null } | null } | null> | null } };

export type TeamMemberQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TeamMemberQuery = { __typename?: 'Query', teamMember: { __typename: 'TeamMember', id: string, name: string, role?: string | null, bio?: string | null, linkedin?: string | null, twitter?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TeamMemberConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamMemberFilter>;
}>;


export type TeamMemberConnectionQuery = { __typename?: 'Query', teamMemberConnection: { __typename?: 'TeamMemberConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TeamMemberConnectionEdges', cursor: string, node?: { __typename: 'TeamMember', id: string, name: string, role?: string | null, bio?: string | null, linkedin?: string | null, twitter?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const SiteSettingsPartsFragmentDoc = gql`
    fragment SiteSettingsParts on SiteSettings {
  __typename
  siteName
  tagline
  phone
  email
  social {
    __typename
    facebook
    twitter
    linkedin
    instagram
    youtube
  }
  companyStats {
    __typename
    value
    label
  }
  trustLogos {
    __typename
    name
    label
  }
}
    `;
export const CoursePartsFragmentDoc = gql`
    fragment CourseParts on Course {
  __typename
  slug
  title
  eyebrow
  tagline
  category
  color
  icon
  image
  summary
  hero {
    __typename
    stats {
      __typename
      value
      label
    }
  }
  outcomes
  modules {
    __typename
    title
    duration
  }
  accreditations
  certificate {
    __typename
    delivery
    validity
    accepted
  }
  priceFrom
  priceNote
  faqs {
    __typename
    q
    a
  }
  enrollId
}
    `;
export const BlogPostPartsFragmentDoc = gql`
    fragment BlogPostParts on BlogPost {
  __typename
  title
  excerpt
  category
  author {
    __typename
    name
    role
  }
  publishedAt
  readMinutes
  heroTone
  heroIcon
  body
}
    `;
export const LegalPagePartsFragmentDoc = gql`
    fragment LegalPageParts on LegalPage {
  __typename
  title
  effectiveDate
  intro
  body
}
    `;
export const FaqGroupPartsFragmentDoc = gql`
    fragment FaqGroupParts on FaqGroup {
  __typename
  category
  order
  items {
    __typename
    q
    a
  }
}
    `;
export const TestimonialPartsFragmentDoc = gql`
    fragment TestimonialParts on Testimonial {
  __typename
  quote
  name
  role
  company
  stat {
    __typename
    value
    label
  }
  featured
  order
}
    `;
export const TeamMemberPartsFragmentDoc = gql`
    fragment TeamMemberParts on TeamMember {
  __typename
  name
  role
  bio
  linkedin
  twitter
  order
}
    `;
export const SiteSettingsDocument = gql`
    query siteSettings($relativePath: String!) {
  siteSettings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteSettingsParts
  }
}
    ${SiteSettingsPartsFragmentDoc}`;
export const SiteSettingsConnectionDocument = gql`
    query siteSettingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteSettingsFilter) {
  siteSettingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteSettingsParts
      }
    }
  }
}
    ${SiteSettingsPartsFragmentDoc}`;
export const CourseDocument = gql`
    query course($relativePath: String!) {
  course(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CourseParts
  }
}
    ${CoursePartsFragmentDoc}`;
export const CourseConnectionDocument = gql`
    query courseConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CourseFilter) {
  courseConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CourseParts
      }
    }
  }
}
    ${CoursePartsFragmentDoc}`;
export const BlogPostDocument = gql`
    query blogPost($relativePath: String!) {
  blogPost(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BlogPostParts
  }
}
    ${BlogPostPartsFragmentDoc}`;
export const BlogPostConnectionDocument = gql`
    query blogPostConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BlogPostFilter) {
  blogPostConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BlogPostParts
      }
    }
  }
}
    ${BlogPostPartsFragmentDoc}`;
export const LegalPageDocument = gql`
    query legalPage($relativePath: String!) {
  legalPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...LegalPageParts
  }
}
    ${LegalPagePartsFragmentDoc}`;
export const LegalPageConnectionDocument = gql`
    query legalPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: LegalPageFilter) {
  legalPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...LegalPageParts
      }
    }
  }
}
    ${LegalPagePartsFragmentDoc}`;
export const FaqGroupDocument = gql`
    query faqGroup($relativePath: String!) {
  faqGroup(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FaqGroupParts
  }
}
    ${FaqGroupPartsFragmentDoc}`;
export const FaqGroupConnectionDocument = gql`
    query faqGroupConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FaqGroupFilter) {
  faqGroupConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FaqGroupParts
      }
    }
  }
}
    ${FaqGroupPartsFragmentDoc}`;
export const TestimonialDocument = gql`
    query testimonial($relativePath: String!) {
  testimonial(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TestimonialParts
  }
}
    ${TestimonialPartsFragmentDoc}`;
export const TestimonialConnectionDocument = gql`
    query testimonialConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TestimonialFilter) {
  testimonialConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TestimonialParts
      }
    }
  }
}
    ${TestimonialPartsFragmentDoc}`;
export const TeamMemberDocument = gql`
    query teamMember($relativePath: String!) {
  teamMember(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TeamMemberParts
  }
}
    ${TeamMemberPartsFragmentDoc}`;
export const TeamMemberConnectionDocument = gql`
    query teamMemberConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TeamMemberFilter) {
  teamMemberConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TeamMemberParts
      }
    }
  }
}
    ${TeamMemberPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      siteSettings(variables: SiteSettingsQueryVariables, options?: C): Promise<{data: SiteSettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsQueryVariables, query: string}> {
        return requester<{data: SiteSettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsQueryVariables, query: string}, SiteSettingsQueryVariables>(SiteSettingsDocument, variables, options);
      },
    siteSettingsConnection(variables?: SiteSettingsConnectionQueryVariables, options?: C): Promise<{data: SiteSettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsConnectionQueryVariables, query: string}> {
        return requester<{data: SiteSettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsConnectionQueryVariables, query: string}, SiteSettingsConnectionQueryVariables>(SiteSettingsConnectionDocument, variables, options);
      },
    course(variables: CourseQueryVariables, options?: C): Promise<{data: CourseQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CourseQueryVariables, query: string}> {
        return requester<{data: CourseQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CourseQueryVariables, query: string}, CourseQueryVariables>(CourseDocument, variables, options);
      },
    courseConnection(variables?: CourseConnectionQueryVariables, options?: C): Promise<{data: CourseConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CourseConnectionQueryVariables, query: string}> {
        return requester<{data: CourseConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CourseConnectionQueryVariables, query: string}, CourseConnectionQueryVariables>(CourseConnectionDocument, variables, options);
      },
    blogPost(variables: BlogPostQueryVariables, options?: C): Promise<{data: BlogPostQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogPostQueryVariables, query: string}> {
        return requester<{data: BlogPostQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogPostQueryVariables, query: string}, BlogPostQueryVariables>(BlogPostDocument, variables, options);
      },
    blogPostConnection(variables?: BlogPostConnectionQueryVariables, options?: C): Promise<{data: BlogPostConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogPostConnectionQueryVariables, query: string}> {
        return requester<{data: BlogPostConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogPostConnectionQueryVariables, query: string}, BlogPostConnectionQueryVariables>(BlogPostConnectionDocument, variables, options);
      },
    legalPage(variables: LegalPageQueryVariables, options?: C): Promise<{data: LegalPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LegalPageQueryVariables, query: string}> {
        return requester<{data: LegalPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LegalPageQueryVariables, query: string}, LegalPageQueryVariables>(LegalPageDocument, variables, options);
      },
    legalPageConnection(variables?: LegalPageConnectionQueryVariables, options?: C): Promise<{data: LegalPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LegalPageConnectionQueryVariables, query: string}> {
        return requester<{data: LegalPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LegalPageConnectionQueryVariables, query: string}, LegalPageConnectionQueryVariables>(LegalPageConnectionDocument, variables, options);
      },
    faqGroup(variables: FaqGroupQueryVariables, options?: C): Promise<{data: FaqGroupQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqGroupQueryVariables, query: string}> {
        return requester<{data: FaqGroupQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqGroupQueryVariables, query: string}, FaqGroupQueryVariables>(FaqGroupDocument, variables, options);
      },
    faqGroupConnection(variables?: FaqGroupConnectionQueryVariables, options?: C): Promise<{data: FaqGroupConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqGroupConnectionQueryVariables, query: string}> {
        return requester<{data: FaqGroupConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqGroupConnectionQueryVariables, query: string}, FaqGroupConnectionQueryVariables>(FaqGroupConnectionDocument, variables, options);
      },
    testimonial(variables: TestimonialQueryVariables, options?: C): Promise<{data: TestimonialQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialQueryVariables, query: string}> {
        return requester<{data: TestimonialQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialQueryVariables, query: string}, TestimonialQueryVariables>(TestimonialDocument, variables, options);
      },
    testimonialConnection(variables?: TestimonialConnectionQueryVariables, options?: C): Promise<{data: TestimonialConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialConnectionQueryVariables, query: string}> {
        return requester<{data: TestimonialConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialConnectionQueryVariables, query: string}, TestimonialConnectionQueryVariables>(TestimonialConnectionDocument, variables, options);
      },
    teamMember(variables: TeamMemberQueryVariables, options?: C): Promise<{data: TeamMemberQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamMemberQueryVariables, query: string}> {
        return requester<{data: TeamMemberQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamMemberQueryVariables, query: string}, TeamMemberQueryVariables>(TeamMemberDocument, variables, options);
      },
    teamMemberConnection(variables?: TeamMemberConnectionQueryVariables, options?: C): Promise<{data: TeamMemberConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamMemberConnectionQueryVariables, query: string}> {
        return requester<{data: TeamMemberConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamMemberConnectionQueryVariables, query: string}, TeamMemberConnectionQueryVariables>(TeamMemberConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "/api/tina/gql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  